name: cffconvert

on:
  push:
    branches:
      - 'master'
      - 'release-*'
    paths:
      - CITATION.cff
  pull_request:
    branches:
      - 'master'
      - 'release-*'
    paths:
      - CITATION.cff

permissions:
  contents: read

jobs:
  validate:
    name: "validate"
    runs-on: ubuntu-latest
    steps:
      - name: Check out a copy of the repository
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
        with:
          persist-credentials: false

      - name: Check whether the citation metadata from CITATION.cff is valid
        uses: citation-file-format/cffconvert-github-action@4cf11baa70a673bfdf9dad0acc7ee33b3f4b6084 # 2.0.0
        with:
          args: "--validate"
