name: Whitespace

permissions: {}

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  whitespace:
    name: Check whitespace
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Checkout the JuliaLang/julia repository
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
        with:
          persist-credentials: false
      - name: Check whitespace
        run: |
          contrib/check-whitespace.jl
